# Generated by Django 5.1.2 on 2024-11-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('year', models.FloatField()),
                ('kilometer', models.FloatField()),
                ('engine', models.CharField(max_length=150)),
                ('actual_price', models.FloatField()),
                ('booking_price', models.FloatField()),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap_app.brand')),
            ],
        ),
    ]
